version: '2.1'

services:
  db:
    build: .
    image: example/db
    container_name: example_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootx
      MYSQL_DATABASE: example
      MYSQL_USER: test
      MYSQL_PASSWORD: test123
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "docker-healthcheck.sh"]
