FROM mysql:5.6.36

#ENV MYSQL_ROOT_PASSWORD root
#ENV MYSQL_DATABASE example
#ENV MYSQL_USER example
#ENV MYSQL_PASSWORD example123

COPY docker-healthcheck.sh /usr/local/bin/
#COPY init-db/setup.sql /docker-entrypoint-initdb.d/

#HEALTHCHECK CMD ["docker-healthcheck.sh"]
