database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: rootx
  url: jdbc:mysql://127.0.0.1:3306/example
  properties:
    charSet: UTF-8

defaultName: myDefaultName

configPaypal:
  apiKey: paypalApiKey

configGoogle:
  apiKey: googleApiKey